version: '3'
services:
  client:
    build: .
    image: bohemus307/music_manager:latest
    depends_on:
      - 'cache'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=prod
      - PGUSER
      - PG_AWS_PASSWORD
      - PGDATABASE
      - NEW_RELIC
      - PROD_DB_HOST
  cache:
    image: redis